export const routes = {
  landing: "/",
  login: "/giris-yap",
  register: "/kayit-ol",
  forgotPassword: "/sifremi-unuttum",
  home: "/ana-menu",
  modes: "/modlar",
  quests: "/gorevler",
  achievements: "/basarimlar",
  collection: "/koleksiyon",
  themes: "/tema-secici",
  profile: "/profil",
  statistics: "/istatistikler",
  dailyReward: "/gunluk-odul",
  settings: "/ayarlar",
  account: "/hesap",
  notifications: "/bildirimler",
  online: "/online",
  tournaments: "/turnuvalar",
  history: "/yarisma-gecmisi",
  onboarding: "/hos-geldin",
} as const;
