import { z } from "zod";

export const exportSchema = z.object({
  surum: z.literal(1),
  disaAktarimTarihi: z.string(),
  profil: z.object({
    gorunenAd: z.string(),
    bio: z.string(),
    unvan: z.string(),
    avatarRenk: z.string(),
    seciliTema: z.string(),
    seciliTahtaTemasi: z.string(),
    seciliEfekt: z.string(),
    romanceSignature: z.string().optional(),
  }),
  ayarlar: z.object({
    temaModu: z.enum(["sistem", "gece", "aydinlik"]),
    temaPaketi: z.string(),
    azaltIlkHareket: z.boolean(),
    yuksekKontrast: z.boolean(),
    grafikYogunlugu: z.enum(["hafif", "dengeli", "yuksek"]),
    anaSes: z.number(),
    muzikSes: z.number(),
    efektSes: z.number(),
    dokunmatikKontroller: z.boolean(),
    bildirimler: z.boolean(),
    titreSimdilik: z.boolean(),
    tusAtamalari: z.record(z.string(), z.string()),
  }),
  progression: z.object({
    xp: z.number(),
    level: z.number(),
    prestige: z.number(),
    stars: z.number(),
    rankedPuan: z.number(),
    gunlukSeri: z.number(),
    modUstaligi: z.record(z.string(), z.unknown()).default({}),
    milestoneDurumu: z.record(z.string(), z.unknown()).default({}),
  }),
  istatistikler: z.object({
    toplamMac: z.number(),
    toplamDakika: z.number(),
    toplamSkor: z.number(),
    enYuksekSkor: z.number(),
    temizlenenToplamSatir: z.number(),
    enUzunCombo: z.number(),
    perfectClearSayisi: z.number(),
    ortalamaMacSuresi: z.number(),
    ortalamaSkor: z.number(),
    gunlukSeri: z.number(),
    acilanOdulSayisi: z.number(),
    basarimTamamlamaOrani: z.number(),
    gorevTamamlamaOrani: z.number(),
    favoriMod: z.enum(["klasik", "rahat", "zen", "sprint", "gorev", "gunluk", "duello"]),
    onlineGalibiyet: z.number(),
    onlineMaglubiyet: z.number(),
    turnuvaKatilim: z.number(),
    enIyiDerece: z.number().nullable().optional(),
    modaGoreMaclar: z.record(z.string(), z.number()).default({}),
    temaKullanimi: z.record(z.string(), z.number()).default({}),
  }),
  kozmetikler: z.array(
    z.object({
      cosmeticId: z.string(),
      unlockedAt: z.string(),
      isEquipped: z.boolean(),
      isFavorite: z.boolean(),
      isNew: z.boolean(),
    }),
  ),
  gorevler: z.array(
    z.object({
      questId: z.string(),
      progress: z.number(),
      goal: z.number(),
      completed: z.boolean(),
      claimedAt: z.string().nullable(),
      resetsAt: z.string().nullable(),
    }),
  ),
  basarimlar: z.array(
    z.object({
      achievementId: z.string(),
      progress: z.number(),
      goal: z.number(),
      unlockedAt: z.string().nullable(),
      claimedAt: z.string().nullable(),
    }),
  ),
  gunlukOduller: z.array(
    z.object({
      dayIndex: z.number(),
      xpAwarded: z.number(),
      rewardId: z.string().nullable(),
      claimedAt: z.string(),
    }),
  ),
  oyunOturumlari: z.array(
    z.object({
      mode: z.enum(["klasik", "rahat", "zen", "sprint", "gorev", "gunluk", "duello"]),
      startedAt: z.string(),
      endedAt: z.string(),
      score: z.number(),
      lines: z.number(),
      level: z.number(),
      comboMax: z.number(),
      perfectClears: z.number(),
      durationMs: z.number(),
      metadata: z.record(z.string(), z.unknown()).default({}),
    }),
  ),
});

export type PersistenceExport = z.infer<typeof exportSchema>;
